const supportedApiVersion = 'v1';

const SECRETKEY_KEY = 'SYNC_SECRETKEY';
const URI_KEY = 'SYNC_URI';

const USERNAME_KEY = 'SYNC_USERNAME';
const HASH_KEY = 'SYNC_HASH';

const ACCESS_TOKEN_KEY = 'SYNC_ACCESS_TOKEN';
const REFRESH_TOKEN_KEY = 'SYNC_REFRESH_TOKEN';

const NONCE_KEY = 'SYNC_NONCE';
